// ============================================================================
// DATOS OFICIALES DE VINCULACIONES Y DESVINCULACIONES 2026 (PERNO & PLANTA SJD)
// ============================================================================

export interface Caso2026Raw {
  id: string;
  tipo_proceso: 'VINCULACION' | 'DESVINCULACION';
  modalidad: 'CARRERA_ADMINISTRATIVA' | 'LIBRE_NOMBRAMIENTO' | 'PROVISIONALIDAD' | 'PRACTICANTE_JUDICANTE';
  id_plaza?: number;
  servidor_nombre: string;
  servidor_cedula: string;
  cargo: string;
  codigo?: string;
  grado?: string;
  dependencia: string;
  causal?: string;
  acto_administrativo?: string;
  fecha_inicio_tramite: string;
  fecha_efectiva?: string;
  etapa_activa_id?: string;
  observaciones?: string;
  estadoValidacionIA?: 'CUMPLE' | 'NO_CUMPLE' | 'REQUIERE_REVISION';
}

export const CASOS_2026_RAW: Caso2026Raw[] = [
  {
    "id": "TR-DESV-2026-001",
    "tipo_proceso": "DESVINCULACION",
    "modalidad": "PROVISIONALIDAD",
    "id_plaza": 150,
    "servidor_nombre": "LEONARDO ARAGON BOHORQUEZ",
    "servidor_cedula": "1012367914",
    "cargo": "AUXILIAR ADMINISTRATIVO",
    "codigo": "407",
    "grado": "15",
    "dependencia": "DIRECCIÓN DE GESTIÓN CORPORATIVA",
    "causal": "Terminación de nombramiento provisional por provisión reglamentaria de vacante",
    "acto_administrativo": "Resolución No. 089 de 2026",
    "fecha_inicio_tramite": "2025-12-31",
    "fecha_efectiva": "2026-01-12",
    "etapa_activa_id": "d_prov_4",
    "observaciones": "Retiro oficial registrado en PERNO con efectividad al 2026-01-12. Trámite de paz y salvos, entrega de inventarios y liquidación presupuestal culminado en Bogdata."
  },
  {
    "id": "TR-DESV-2026-002",
    "tipo_proceso": "DESVINCULACION",
    "modalidad": "PROVISIONALIDAD",
    "id_plaza": 136,
    "servidor_nombre": "ANGIE GERALDINE MURILLO FULA",
    "servidor_cedula": "1010220018",
    "cargo": "TECNICO OPERATIVO",
    "codigo": "314",
    "grado": "9",
    "dependencia": "DIRECCIÓN DISTRITAL DE DOCTRINA Y ASUNTOS NORMATIVOS",
    "causal": "Terminación de nombramiento provisional por provisión reglamentaria de vacante",
    "acto_administrativo": "Resolución No. 339 de 2026",
    "fecha_inicio_tramite": "2025-12-31",
    "fecha_efectiva": "2026-01-12",
    "etapa_activa_id": "d_prov_4",
    "observaciones": "Retiro oficial registrado en PERNO con efectividad al 2026-01-12. Trámite de paz y salvos, entrega de inventarios y liquidación presupuestal culminado en Bogdata."
  },
  {
    "id": "TR-DESV-2026-003",
    "tipo_proceso": "DESVINCULACION",
    "modalidad": "PROVISIONALIDAD",
    "id_plaza": 162,
    "servidor_nombre": "JUAN SEBASTIAN RIAÑO HERNANDEZ",
    "servidor_cedula": "1136879957",
    "cargo": "SECRETARIO",
    "codigo": "440",
    "grado": "9",
    "dependencia": "DIRECCIÓN DISTRITAL DE DOCTRINA Y ASUNTOS NORMATIVOS",
    "causal": "Terminación de nombramiento provisional por provisión reglamentaria de vacante",
    "acto_administrativo": "Resolución No. 176 de 2026",
    "fecha_inicio_tramite": "2026-01-03",
    "fecha_efectiva": "2026-01-15",
    "etapa_activa_id": "d_prov_4",
    "observaciones": "Retiro oficial registrado en PERNO con efectividad al 2026-01-15. Trámite de paz y salvos, entrega de inventarios y liquidación presupuestal culminado en Bogdata."
  },
  {
    "id": "TR-DESV-2026-004",
    "tipo_proceso": "DESVINCULACION",
    "modalidad": "PROVISIONALIDAD",
    "id_plaza": 118,
    "servidor_nombre": "FAVER PEREZ GUTIERREZ",
    "servidor_cedula": "1030602070",
    "cargo": "TECNICO OPERATIVO",
    "codigo": "314",
    "grado": "20",
    "dependencia": "OFICINA DE TECNOLOGÃAS DE LA INFORMACIÓN Y LAS COMUNICACIONES",
    "causal": "Terminación de nombramiento provisional por provisión reglamentaria de vacante",
    "acto_administrativo": "Resolución No. 206 de 2026",
    "fecha_inicio_tramite": "2026-01-14",
    "fecha_efectiva": "2026-01-26",
    "etapa_activa_id": "d_prov_4",
    "observaciones": "Retiro oficial registrado en PERNO con efectividad al 2026-01-26. Trámite de paz y salvos, entrega de inventarios y liquidación presupuestal culminado en Bogdata."
  },
  {
    "id": "TR-DESV-2026-005",
    "tipo_proceso": "DESVINCULACION",
    "modalidad": "PROVISIONALIDAD",
    "id_plaza": 163,
    "servidor_nombre": "HEIDY LORENA ROMERO TORRES",
    "servidor_cedula": "1023894175",
    "cargo": "AUXILIAR ADMINISTRATIVO",
    "codigo": "407",
    "grado": "11",
    "dependencia": "DIRECCIÓN DE GESTIÓN CORPORATIVA",
    "causal": "Terminación de nombramiento provisional por provisión reglamentaria de vacante",
    "acto_administrativo": "Resolución No. 263 de 2026",
    "fecha_inicio_tramite": "2026-02-17",
    "fecha_efectiva": "2026-03-01",
    "etapa_activa_id": "d_prov_4",
    "observaciones": "Retiro oficial registrado en PERNO con efectividad al 2026-03-01. Trámite de paz y salvos, entrega de inventarios y liquidación presupuestal culminado en Bogdata."
  },
  {
    "id": "TR-DESV-2026-006",
    "tipo_proceso": "DESVINCULACION",
    "modalidad": "CARRERA_ADMINISTRATIVA",
    "id_plaza": 116,
    "servidor_nombre": "JORGE ANDRES ROJAS PEÑA",
    "servidor_cedula": "1015393324",
    "cargo": "PROFESIONAL UNIVERSITARIO",
    "codigo": "219",
    "grado": "1",
    "dependencia": "DIRECCIÓN DISTRITAL DE INSPECCIÓN, VIGILANCIA Y CONTROL",
    "causal": "Renuncia regularmente aceptada (Ley 909 de 2004, Art. 41 lit. a)",
    "acto_administrativo": "Resolución No. 121 de 2026",
    "fecha_inicio_tramite": "2026-02-17",
    "fecha_efectiva": "2026-03-01",
    "etapa_activa_id": "d_carr_4",
    "observaciones": "Retiro oficial registrado en PERNO con efectividad al 2026-03-01. Trámite de paz y salvos, entrega de inventarios y liquidación presupuestal culminado en Bogdata."
  },
  {
    "id": "TR-DESV-2026-007",
    "tipo_proceso": "DESVINCULACION",
    "modalidad": "PROVISIONALIDAD",
    "id_plaza": 108,
    "servidor_nombre": "LUZ ESPERANZA GARCIA CARDONA",
    "servidor_cedula": "52768137",
    "cargo": "PROFESIONAL UNIVERSITARIO",
    "codigo": "219",
    "grado": "18",
    "dependencia": "DIRECCIÓN DE GESTIÓN CORPORATIVA",
    "causal": "Terminación de nombramiento provisional por provisión reglamentaria de vacante",
    "acto_administrativo": "Resolución No. 062 de 2026",
    "fecha_inicio_tramite": "2026-02-20",
    "fecha_efectiva": "2026-03-04",
    "etapa_activa_id": "d_prov_4",
    "observaciones": "Retiro oficial registrado en PERNO con efectividad al 2026-03-04. Trámite de paz y salvos, entrega de inventarios y liquidación presupuestal culminado en Bogdata."
  },
  {
    "id": "TR-DESV-2026-008",
    "tipo_proceso": "DESVINCULACION",
    "modalidad": "PROVISIONALIDAD",
    "id_plaza": 156,
    "servidor_nombre": "WILSON RAMON HURTADO TORRES",
    "servidor_cedula": "7690438",
    "cargo": "CONDUCTOR",
    "codigo": "480",
    "grado": "13",
    "dependencia": "DIRECCIÓN DE GESTIÓN CORPORATIVA",
    "causal": "Terminación de nombramiento provisional por provisión reglamentaria de vacante",
    "acto_administrativo": "Resolución No. 025 de 2026",
    "fecha_inicio_tramite": "2026-02-21",
    "fecha_efectiva": "2026-03-05",
    "etapa_activa_id": "d_prov_4",
    "observaciones": "Retiro oficial registrado en PERNO con efectividad al 2026-03-05. Trámite de paz y salvos, entrega de inventarios y liquidación presupuestal culminado en Bogdata."
  },
  {
    "id": "TR-DESV-2026-009",
    "tipo_proceso": "DESVINCULACION",
    "modalidad": "PROVISIONALIDAD",
    "id_plaza": 149,
    "servidor_nombre": "ASHLEY JHOANNA RAMIREZ RUEDA",
    "servidor_cedula": "1031178594",
    "cargo": "AUXILIAR ADMINISTRATIVO",
    "codigo": "407",
    "grado": "15",
    "dependencia": "DIRECCIÓN DE GESTIÓN CORPORATIVA",
    "causal": "Terminación de nombramiento provisional por provisión reglamentaria de vacante",
    "acto_administrativo": "Resolución No. 394 de 2026",
    "fecha_inicio_tramite": "2026-02-24",
    "fecha_efectiva": "2026-03-08",
    "etapa_activa_id": "d_prov_4",
    "observaciones": "Retiro oficial registrado en PERNO con efectividad al 2026-03-08. Trámite de paz y salvos, entrega de inventarios y liquidación presupuestal culminado en Bogdata."
  },
  {
    "id": "TR-DESV-2026-010",
    "tipo_proceso": "DESVINCULACION",
    "modalidad": "CARRERA_ADMINISTRATIVA",
    "id_plaza": 34,
    "servidor_nombre": "GLORIA MAGDALENA DIAGO CASASBUENAS",
    "servidor_cedula": "51569861",
    "cargo": "PROFESIONAL ESPECIALIZADO",
    "codigo": "222",
    "grado": "27",
    "dependencia": "DIRECCIÓN DISTRITAL DE GESTIÓN JUDICIAL",
    "causal": "Renuncia regularmente aceptada (Ley 909 de 2004, Art. 41 lit. a)",
    "acto_administrativo": "Resolución No. 002 de 2026",
    "fecha_inicio_tramite": "2026-04-06",
    "fecha_efectiva": "2026-04-18",
    "etapa_activa_id": "d_carr_4",
    "observaciones": "Retiro oficial registrado en PERNO con efectividad al 2026-04-18. Trámite de paz y salvos, entrega de inventarios y liquidación presupuestal culminado en Bogdata."
  },
  {
    "id": "TR-DESV-2026-011",
    "tipo_proceso": "DESVINCULACION",
    "modalidad": "PROVISIONALIDAD",
    "id_plaza": 155,
    "servidor_nombre": "ESTEFANIA ORTEGA CESPEDES",
    "servidor_cedula": "1000774068",
    "cargo": "AUXILIAR ADMINISTRATIVO",
    "codigo": "407",
    "grado": "9",
    "dependencia": "DIRECCIÓN DISTRITAL DE INSPECCIÓN, VIGILANCIA Y CONTROL",
    "causal": "Terminación de nombramiento provisional por provisión reglamentaria de vacante",
    "acto_administrativo": "Resolución No. 077 de 2026",
    "fecha_inicio_tramite": "2026-04-21",
    "fecha_efectiva": "2026-05-03",
    "etapa_activa_id": "d_prov_4",
    "observaciones": "Retiro oficial registrado en PERNO con efectividad al 2026-05-03. Trámite de paz y salvos, entrega de inventarios y liquidación presupuestal culminado en Bogdata."
  },
  {
    "id": "TR-DESV-2026-012",
    "tipo_proceso": "DESVINCULACION",
    "modalidad": "CARRERA_ADMINISTRATIVA",
    "id_plaza": 148,
    "servidor_nombre": "MARIA CRISTINA VANEGAS LARGO",
    "servidor_cedula": "39773518",
    "cargo": "AUXILIAR ADMINISTRATIVO",
    "codigo": "407",
    "grado": "15",
    "dependencia": "DIRECCIÓN DISTRITAL DE DOCTRINA Y ASUNTOS NORMATIVOS",
    "causal": "Pensión de vejez / Jubilación con reconocimiento de mesada pensional",
    "acto_administrativo": "Resolución No. 002 de 2026",
    "fecha_inicio_tramite": "2026-05-19",
    "fecha_efectiva": "2026-05-31",
    "etapa_activa_id": "d_carr_4",
    "observaciones": "Retiro oficial registrado en PERNO con efectividad al 2026-05-31. Trámite de paz y salvos, entrega de inventarios y liquidación presupuestal culminado en Bogdata."
  },
  {
    "id": "TR-DESV-2026-013",
    "tipo_proceso": "DESVINCULACION",
    "modalidad": "LIBRE_NOMBRAMIENTO",
    "id_plaza": 3,
    "servidor_nombre": "MARIA CATALINA JARAMILLO GONZALEZ",
    "servidor_cedula": "52699744",
    "cargo": "DIRECTOR TECNICO",
    "codigo": "9",
    "grado": "7",
    "dependencia": "DIRECCIÓN DISTRITAL DE POLÃTICA JURÃDICA",
    "causal": "Declaratoria de insubsistencia / Remoción ordinaria o renuncia aceptada",
    "acto_administrativo": "Resolución No. 288 de 2026",
    "fecha_inicio_tramite": "2026-05-22",
    "fecha_efectiva": "2026-06-03",
    "etapa_activa_id": "d_lnr_4",
    "observaciones": "Retiro oficial registrado en PERNO con efectividad al 2026-06-03. Trámite de paz y salvos, entrega de inventarios y liquidación presupuestal culminado en Bogdata."
  },
  {
    "id": "TR-DESV-2026-014",
    "tipo_proceso": "DESVINCULACION",
    "modalidad": "PROVISIONALIDAD",
    "id_plaza": 133,
    "servidor_nombre": "DAYANNA LORENA VELASQUEZ FLOREZ",
    "servidor_cedula": "1018499480",
    "cargo": "TECNICO OPERATIVO",
    "codigo": "314",
    "grado": "15",
    "dependencia": "DIRECCIÓN DISTRITAL DE POLÃTICA JURÃDICA",
    "causal": "Terminación de nombramiento provisional por provisión reglamentaria de vacante",
    "acto_administrativo": "Resolución No. 171 de 2026",
    "fecha_inicio_tramite": "2026-06-03",
    "fecha_efectiva": "2026-06-15",
    "etapa_activa_id": "d_prov_4",
    "observaciones": "Retiro oficial registrado en PERNO con efectividad al 2026-06-15. Trámite de paz y salvos, entrega de inventarios y liquidación presupuestal culminado en Bogdata."
  },
  {
    "id": "TR-DESV-2026-015",
    "tipo_proceso": "DESVINCULACION",
    "modalidad": "PROVISIONALIDAD",
    "id_plaza": 106,
    "servidor_nombre": "DIANA CAROLINA CASTILLO OTALORA",
    "servidor_cedula": "1130593147",
    "cargo": "PROFESIONAL UNIVERSITARIO",
    "codigo": "219",
    "grado": "9",
    "dependencia": "OFICINA ASESORA DE PLANEACIÓN",
    "causal": "Terminación de nombramiento provisional por provisión reglamentaria de vacante",
    "acto_administrativo": "Resolución No. 016 de 2026",
    "fecha_inicio_tramite": "2026-06-18",
    "fecha_efectiva": "2026-06-30",
    "etapa_activa_id": "d_prov_4",
    "observaciones": "Retiro oficial registrado en PERNO con efectividad al 2026-06-30. Trámite de paz y salvos, entrega de inventarios y liquidación presupuestal culminado en Bogdata."
  },
  {
    "id": "TR-DESV-2026-016",
    "tipo_proceso": "DESVINCULACION",
    "modalidad": "CARRERA_ADMINISTRATIVA",
    "id_plaza": 141,
    "servidor_nombre": "BLAYITD SOLEY JIMENEZ RODRIGUEZ",
    "servidor_cedula": "1075680600",
    "cargo": "AUXILIAR ADMINISTRATIVO",
    "codigo": "407",
    "grado": "20",
    "dependencia": "DESPACHO SECRETARÃA JURÃDICA",
    "causal": "Pensión de vejez / Jubilación con reconocimiento de mesada pensional",
    "acto_administrativo": "Resolución No. 070 de 2026",
    "fecha_inicio_tramite": "2026-06-23",
    "fecha_efectiva": "2026-07-05",
    "etapa_activa_id": "d_carr_4",
    "observaciones": "Retiro oficial registrado en PERNO con efectividad al 2026-07-05. Trámite de paz y salvos, entrega de inventarios y liquidación presupuestal culminado en Bogdata."
  },
  {
    "id": "TR-DESV-2026-017",
    "tipo_proceso": "DESVINCULACION",
    "modalidad": "CARRERA_ADMINISTRATIVA",
    "id_plaza": 40,
    "servidor_nombre": "DONALDO YAMITH ZABALETA TABOADA",
    "servidor_cedula": "1064976255",
    "cargo": "PROFESIONAL ESPECIALIZADO",
    "codigo": "222",
    "grado": "27",
    "dependencia": "DIRECCIÓN DISTRITAL DE GESTIÓN JUDICIAL",
    "causal": "Renuncia regularmente aceptada (Ley 909 de 2004, Art. 41 lit. a)",
    "acto_administrativo": "Resolución No. 093 de 2026",
    "fecha_inicio_tramite": "2026-07-14",
    "fecha_efectiva": "2026-07-26",
    "etapa_activa_id": "d_carr_4",
    "observaciones": "Retiro oficial registrado en PERNO con efectividad al 2026-07-26. Trámite de paz y salvos, entrega de inventarios y liquidación presupuestal culminado en Bogdata."
  },
  {
    "id": "TR-DESV-2026-018",
    "tipo_proceso": "DESVINCULACION",
    "modalidad": "PROVISIONALIDAD",
    "id_plaza": 152,
    "servidor_nombre": "OMAIRA ALONSO BERNAL",
    "servidor_cedula": "52115141",
    "cargo": "AUXILIAR ADMINISTRATIVO",
    "codigo": "407",
    "grado": "13",
    "dependencia": "SUBSECRETARÃA JURÃDICA",
    "causal": "Terminación de nombramiento provisional por provisión reglamentaria de vacante",
    "acto_administrativo": "Resolución No. 058 de 2026",
    "fecha_inicio_tramite": "2026-07-21",
    "fecha_efectiva": "2026-08-02",
    "etapa_activa_id": "d_prov_4",
    "observaciones": "Retiro oficial registrado en PERNO con efectividad al 2026-08-02. Trámite de paz y salvos, entrega de inventarios y liquidación presupuestal culminado en Bogdata."
  },
  {
    "id": "TR-DESV-2026-019",
    "tipo_proceso": "DESVINCULACION",
    "modalidad": "LIBRE_NOMBRAMIENTO",
    "id_plaza": 11,
    "servidor_nombre": "ANA MARTA MIRANDA CORRALES",
    "servidor_cedula": "36697863",
    "cargo": "JEFE OFICINA ASESORA",
    "codigo": "115",
    "grado": "6",
    "dependencia": "OFICINA ASESORA DE PLANEACIÓN",
    "causal": "Declaratoria de insubsistencia / Remoción ordinaria o renuncia aceptada",
    "acto_administrativo": "Resolución No. 417 de 2026",
    "fecha_inicio_tramite": "2026-08-07",
    "fecha_efectiva": "2026-08-19",
    "etapa_activa_id": "d_lnr_4",
    "observaciones": "Retiro oficial registrado en PERNO con efectividad al 2026-08-19. Trámite de paz y salvos, entrega de inventarios y liquidación presupuestal culminado en Bogdata."
  },
  {
    "id": "TR-DESV-2026-020",
    "tipo_proceso": "DESVINCULACION",
    "modalidad": "CARRERA_ADMINISTRATIVA",
    "id_plaza": 65,
    "servidor_nombre": "JENIFFER GUTIERREZ GUTIERREZ",
    "servidor_cedula": "53066719",
    "cargo": "PROFESIONAL ESPECIALIZADO",
    "codigo": "222",
    "grado": "21",
    "dependencia": "DIRECCIÓN DISTRITAL DE INSPECCIÓN, VIGILANCIA Y CONTROL",
    "causal": "Renuncia regularmente aceptada (Ley 909 de 2004, Art. 41 lit. a)",
    "acto_administrativo": "Resolución No. 199 de 2026",
    "fecha_inicio_tramite": "2026-08-19",
    "fecha_efectiva": "2026-08-31",
    "etapa_activa_id": "d_carr_4",
    "observaciones": "Retiro oficial registrado en PERNO con efectividad al 2026-08-31. Trámite de paz y salvos, entrega de inventarios y liquidación presupuestal culminado en Bogdata."
  },
  {
    "id": "TR-DESV-2026-021",
    "tipo_proceso": "DESVINCULACION",
    "modalidad": "LIBRE_NOMBRAMIENTO",
    "id_plaza": 4,
    "servidor_nombre": "MARIA PAULA RUEDA MANTILLA",
    "servidor_cedula": "53014890",
    "cargo": "SUBSECRETARIO DE DESPACHO",
    "codigo": "45",
    "grado": "8",
    "dependencia": "SUBSECRETARÃA JURÃDICA",
    "causal": "Declaratoria de insubsistencia / Remoción ordinaria o renuncia aceptada",
    "acto_administrativo": "Resolución No. 400 de 2026",
    "fecha_inicio_tramite": "2026-08-19",
    "fecha_efectiva": "2026-08-31",
    "etapa_activa_id": "d_lnr_4",
    "observaciones": "Retiro oficial registrado en PERNO con efectividad al 2026-08-31. Trámite de paz y salvos, entrega de inventarios y liquidación presupuestal culminado en Bogdata."
  },
  {
    "id": "TR-DESV-2026-022",
    "tipo_proceso": "DESVINCULACION",
    "modalidad": "PRACTICANTE_JUDICANTE",
    "servidor_nombre": "VALENTINA GÓMEZ MARTÍNEZ",
    "servidor_cedula": "1019284712",
    "cargo": "JUDICANTE AD-HONOREM",
    "dependencia": "DIRECCIÓN DISTRITAL DE ESTUDIOS",
    "causal": "Culminación regular del período formativo / judicatura acordada (Ley 2043 de 2020)",
    "fecha_inicio_tramite": "2026-04-08",
    "fecha_efectiva": "2026-04-20",
    "etapa_activa_id": "d_prac_4",
    "observaciones": "Período formativo culminado con evaluación sobresaliente del tutor. Retiro de ARL tramitado y Certificación Final expedida con validez de experiencia profesional."
  },
  {
    "id": "TR-VINC-2026-001",
    "tipo_proceso": "VINCULACION",
    "modalidad": "LIBRE_NOMBRAMIENTO",
    "id_plaza": 51,
    "servidor_nombre": "LEIDY YULIETH PEREA RAMIREZ",
    "servidor_cedula": "1075208323",
    "cargo": "JEFE DE OFICINA",
    "codigo": "6",
    "grado": "6",
    "dependencia": "OFICINA DE CONTROL INTERNO",
    "acto_administrativo": "Resolución No. 674 de 2026",
    "fecha_inicio_tramite": "2025-12-26",
    "fecha_efectiva": "2026-01-09",
    "etapa_activa_id": "v_lnr_4",
    "observaciones": "Vinculación formalizada e incorporada a la nómina institucional en vigencia 2026. Verificación de antecedentes y posesión surtida conforme a la Ley 909 de 2004."
  },
  {
    "id": "TR-VINC-2026-002",
    "tipo_proceso": "VINCULACION",
    "modalidad": "CARRERA_ADMINISTRATIVA",
    "id_plaza": 17,
    "servidor_nombre": "MARLY YULY ROJAS LAIDEO",
    "servidor_cedula": "1098632731",
    "cargo": "SECRETARIO EJECUTIVO",
    "codigo": "425",
    "grado": "20",
    "dependencia": "DIRECCIÓN DE GESTIÓN CORPORATIVA",
    "acto_administrativo": "Resolución No. 061 de 2026",
    "fecha_inicio_tramite": "2026-02-09",
    "fecha_efectiva": "2026-02-23",
    "etapa_activa_id": "v_carr_4",
    "observaciones": "Vinculación formalizada e incorporada a la nómina institucional en vigencia 2026. Verificación de antecedentes y posesión surtida conforme a la Ley 909 de 2004."
  },
  {
    "id": "TR-VINC-2026-003",
    "tipo_proceso": "VINCULACION",
    "modalidad": "CARRERA_ADMINISTRATIVA",
    "id_plaza": 101,
    "servidor_nombre": "ANDREA DEL PILAR CARDENAS SARMIENTO",
    "servidor_cedula": "52429411",
    "cargo": "PROFESIONAL ESPECIALIZADO",
    "codigo": "222",
    "grado": "19",
    "dependencia": "DIRECCIÓN DISTRITAL DE ASUNTOS DISCIPLINARIOS",
    "acto_administrativo": "Resolución No. 068 de 2026",
    "fecha_inicio_tramite": "2026-02-16",
    "fecha_efectiva": "2026-03-02",
    "etapa_activa_id": "v_carr_4",
    "observaciones": "Vinculación formalizada e incorporada a la nómina institucional en vigencia 2026. Verificación de antecedentes y posesión surtida conforme a la Ley 909 de 2004."
  },
  {
    "id": "TR-VINC-2026-004",
    "tipo_proceso": "VINCULACION",
    "modalidad": "CARRERA_ADMINISTRATIVA",
    "id_plaza": 33,
    "servidor_nombre": "ERIKA MARCELA MEDINA SANTANA",
    "servidor_cedula": "42163264",
    "cargo": "AUXILIAR ADMINISTRATIVO",
    "codigo": "407",
    "grado": "11",
    "dependencia": "DIRECCIÓN DE GESTIÓN CORPORATIVA",
    "acto_administrativo": "Resolución No. 060 de 2026",
    "fecha_inicio_tramite": "2026-02-16",
    "fecha_efectiva": "2026-03-02",
    "etapa_activa_id": "v_carr_4",
    "observaciones": "Vinculación formalizada e incorporada a la nómina institucional en vigencia 2026. Verificación de antecedentes y posesión surtida conforme a la Ley 909 de 2004."
  },
  {
    "id": "TR-VINC-2026-005",
    "tipo_proceso": "VINCULACION",
    "modalidad": "CARRERA_ADMINISTRATIVA",
    "id_plaza": 132,
    "servidor_nombre": "ELIANA STEPHANIE ASTAIZA CHAVES",
    "servidor_cedula": "1085273461",
    "cargo": "PROFESIONAL UNIVERSITARIO",
    "codigo": "219",
    "grado": "15",
    "dependencia": "DIRECCIÓN DISTRITAL DE INSPECCIÓN, VIGILANCIA Y CONTROL",
    "acto_administrativo": "Resolución No. 069 de 2026",
    "fecha_inicio_tramite": "2026-02-16",
    "fecha_efectiva": "2026-03-02",
    "etapa_activa_id": "v_carr_4",
    "observaciones": "Vinculación formalizada e incorporada a la nómina institucional en vigencia 2026. Verificación de antecedentes y posesión surtida conforme a la Ley 909 de 2004."
  },
  {
    "id": "TR-VINC-2026-006",
    "tipo_proceso": "VINCULACION",
    "modalidad": "CARRERA_ADMINISTRATIVA",
    "id_plaza": 107,
    "servidor_nombre": "GIOVANNY ALEXANDER CORTES PACHON",
    "servidor_cedula": "79967554",
    "cargo": "PROFESIONAL UNIVERSITARIO",
    "codigo": "219",
    "grado": "18",
    "dependencia": "DIRECCIÓN DE GESTIÓN CORPORATIVA",
    "acto_administrativo": "Resolución No. 055 de 2026",
    "fecha_inicio_tramite": "2026-02-19",
    "fecha_efectiva": "2026-03-05",
    "etapa_activa_id": "v_carr_4",
    "observaciones": "Vinculación formalizada e incorporada a la nómina institucional en vigencia 2026. Verificación de antecedentes y posesión surtida conforme a la Ley 909 de 2004."
  },
  {
    "id": "TR-VINC-2026-007",
    "tipo_proceso": "VINCULACION",
    "modalidad": "CARRERA_ADMINISTRATIVA",
    "id_plaza": 29,
    "servidor_nombre": "LUIS DAUVINY DUARTE ROA",
    "servidor_cedula": "79417068",
    "cargo": "CONDUCTOR",
    "codigo": "480",
    "grado": "13",
    "dependencia": "DIRECCIÓN DE GESTIÓN CORPORATIVA",
    "acto_administrativo": "Resolución No. 054 de 2026",
    "fecha_inicio_tramite": "2026-02-20",
    "fecha_efectiva": "2026-03-06",
    "etapa_activa_id": "v_carr_4",
    "observaciones": "Vinculación formalizada e incorporada a la nómina institucional en vigencia 2026. Verificación de antecedentes y posesión surtida conforme a la Ley 909 de 2004."
  },
  {
    "id": "TR-VINC-2026-008",
    "tipo_proceso": "VINCULACION",
    "modalidad": "CARRERA_ADMINISTRATIVA",
    "servidor_nombre": "BLAYITD SOLEY JIMENEZ RODRIGUEZ",
    "servidor_cedula": "1075680600",
    "cargo": "AUXILIAR ADMINISTRATIVO",
    "codigo": "407",
    "grado": "20",
    "dependencia": "DESPACHO SECRETARÃA JURÃDICA",
    "acto_administrativo": "Resolución No. 070 de 2026",
    "fecha_inicio_tramite": "2026-02-23",
    "fecha_efectiva": "2026-03-09",
    "etapa_activa_id": "v_carr_4",
    "observaciones": "Vinculación formalizada e incorporada a la nómina institucional en vigencia 2026. Verificación de antecedentes y posesión surtida conforme a la Ley 909 de 2004."
  },
  {
    "id": "TR-VINC-2026-009",
    "tipo_proceso": "VINCULACION",
    "modalidad": "CARRERA_ADMINISTRATIVA",
    "id_plaza": 122,
    "servidor_nombre": "HUGO ALFONSO CABARCAS AYOLA",
    "servidor_cedula": "8980601",
    "cargo": "PROFESIONAL UNIVERSITARIO",
    "codigo": "219",
    "grado": "18",
    "dependencia": "DIRECCIÓN DISTRITAL DE INSPECCIÓN, VIGILANCIA Y CONTROL",
    "acto_administrativo": "Resolución No. 063 de 2026",
    "fecha_inicio_tramite": "2026-02-24",
    "fecha_efectiva": "2026-03-10",
    "etapa_activa_id": "v_carr_4",
    "observaciones": "Vinculación formalizada e incorporada a la nómina institucional en vigencia 2026. Verificación de antecedentes y posesión surtida conforme a la Ley 909 de 2004."
  },
  {
    "id": "TR-VINC-2026-010",
    "tipo_proceso": "VINCULACION",
    "modalidad": "CARRERA_ADMINISTRATIVA",
    "id_plaza": 83,
    "servidor_nombre": "LUZ ANDREA CUBILLOS GUALDRON",
    "servidor_cedula": "52430229",
    "cargo": "PROFESIONAL ESPECIALIZADO",
    "codigo": "222",
    "grado": "24",
    "dependencia": "DIRECCIÓN DISTRITAL DE DOCTRINA Y ASUNTOS NORMATIVOS",
    "acto_administrativo": "Resolución No. 056 de 2026",
    "fecha_inicio_tramite": "2026-03-02",
    "fecha_efectiva": "2026-03-16",
    "etapa_activa_id": "v_carr_4",
    "observaciones": "Vinculación formalizada e incorporada a la nómina institucional en vigencia 2026. Verificación de antecedentes y posesión surtida conforme a la Ley 909 de 2004."
  },
  {
    "id": "TR-VINC-2026-011",
    "tipo_proceso": "VINCULACION",
    "modalidad": "CARRERA_ADMINISTRATIVA",
    "id_plaza": 77,
    "servidor_nombre": "ANGELA MARCELA RODRIGUEZ DIAZ",
    "servidor_cedula": "42161948",
    "cargo": "PROFESIONAL ESPECIALIZADO",
    "codigo": "222",
    "grado": "26",
    "dependencia": "DIRECCIÓN DE GESTIÓN CORPORATIVA",
    "acto_administrativo": "Resolución No. 057 de 2026",
    "fecha_inicio_tramite": "2026-03-04",
    "fecha_efectiva": "2026-03-18",
    "etapa_activa_id": "v_carr_4",
    "observaciones": "Vinculación formalizada e incorporada a la nómina institucional en vigencia 2026. Verificación de antecedentes y posesión surtida conforme a la Ley 909 de 2004."
  },
  {
    "id": "TR-VINC-2026-012",
    "tipo_proceso": "VINCULACION",
    "modalidad": "CARRERA_ADMINISTRATIVA",
    "id_plaza": 152,
    "servidor_nombre": "RODRIGO DIDIER MUÑOZ CONTRERAS",
    "servidor_cedula": "79994178",
    "cargo": "TECNICO OPERATIVO",
    "codigo": "314",
    "grado": "20",
    "dependencia": "OFICINA DE TECNOLOGÃAS DE LA INFORMACIÓN Y LAS COMUNICACIONES",
    "acto_administrativo": "Resolución No. 059 de 2026",
    "fecha_inicio_tramite": "2026-04-08",
    "fecha_efectiva": "2026-04-22",
    "etapa_activa_id": "v_carr_4",
    "observaciones": "Vinculación formalizada e incorporada a la nómina institucional en vigencia 2026. Verificación de antecedentes y posesión surtida conforme a la Ley 909 de 2004."
  },
  {
    "id": "TR-VINC-2026-013",
    "tipo_proceso": "VINCULACION",
    "modalidad": "CARRERA_ADMINISTRATIVA",
    "id_plaza": 128,
    "servidor_nombre": "ANDRES FABIAN NOSSA GUZMAN",
    "servidor_cedula": "80826518",
    "cargo": "PROFESIONAL UNIVERSITARIO",
    "codigo": "219",
    "grado": "18",
    "dependencia": "DIRECCIÓN DISTRITAL DE INSPECCIÓN, VIGILANCIA Y CONTROL",
    "acto_administrativo": "Resolución No. 219 de 2026",
    "fecha_inicio_tramite": "2026-06-03",
    "fecha_efectiva": "2026-06-17",
    "etapa_activa_id": "v_carr_4",
    "observaciones": "Vinculación formalizada e incorporada a la nómina institucional en vigencia 2026. Verificación de antecedentes y posesión surtida conforme a la Ley 909 de 2004."
  },
  {
    "id": "TR-VINC-2026-014",
    "tipo_proceso": "VINCULACION",
    "modalidad": "CARRERA_ADMINISTRATIVA",
    "id_plaza": 133,
    "servidor_nombre": "MAGDA PATRICIA PUENTES PARDO",
    "servidor_cedula": "52519358",
    "cargo": "PROFESIONAL UNIVERSITARIO",
    "codigo": "219",
    "grado": "15",
    "dependencia": "DIRECCIÓN DISTRITAL DE INSPECCIÓN, VIGILANCIA Y CONTROL",
    "acto_administrativo": "Resolución No. 220 de 2026",
    "fecha_inicio_tramite": "2026-06-17",
    "fecha_efectiva": "2026-07-01",
    "etapa_activa_id": "v_carr_4",
    "observaciones": "Vinculación formalizada e incorporada a la nómina institucional en vigencia 2026. Verificación de antecedentes y posesión surtida conforme a la Ley 909 de 2004."
  },
  {
    "id": "TR-VINC-2026-015",
    "tipo_proceso": "VINCULACION",
    "modalidad": "CARRERA_ADMINISTRATIVA",
    "id_plaza": 103,
    "servidor_nombre": "LEIDY VANESSA NIETO ROJAS",
    "servidor_cedula": "1010213468",
    "cargo": "PROFESIONAL ESPECIALIZADO",
    "codigo": "222",
    "grado": "19",
    "dependencia": "DIRECCIÓN DISTRITAL DE INSPECCIÓN, VIGILANCIA Y CONTROL",
    "acto_administrativo": "Resolución No. 236 de 2026",
    "fecha_inicio_tramite": "2026-07-07",
    "fecha_efectiva": "2026-07-21",
    "etapa_activa_id": "v_carr_4",
    "observaciones": "Vinculación formalizada e incorporada a la nómina institucional en vigencia 2026. Verificación de antecedentes y posesión surtida conforme a la Ley 909 de 2004."
  },
  {
    "id": "TR-VINC-2026-016",
    "tipo_proceso": "VINCULACION",
    "modalidad": "CARRERA_ADMINISTRATIVA",
    "id_plaza": 84,
    "servidor_nombre": "DANIEL YIDID GRANADOS GELVES",
    "servidor_cedula": "91526810",
    "cargo": "PROFESIONAL ESPECIALIZADO",
    "codigo": "222",
    "grado": "24",
    "dependencia": "DIRECCIÓN DISTRITAL DE DOCTRINA Y ASUNTOS NORMATIVOS",
    "acto_administrativo": "Resolución No. 330 de 2026",
    "fecha_inicio_tramite": "2026-07-15",
    "fecha_efectiva": "2026-07-29",
    "etapa_activa_id": "v_carr_4",
    "observaciones": "Vinculación formalizada e incorporada a la nómina institucional en vigencia 2026. Verificación de antecedentes y posesión surtida conforme a la Ley 909 de 2004."
  },
  {
    "id": "TR-VINC-2026-017",
    "tipo_proceso": "VINCULACION",
    "modalidad": "LIBRE_NOMBRAMIENTO",
    "id_plaza": 49,
    "servidor_nombre": "MARIA FERNANDA FUENTES TUTA",
    "servidor_cedula": "52966706",
    "cargo": "DIRECTOR TECNICO",
    "codigo": "9",
    "grado": "7",
    "dependencia": "DIRECCIÓN DISTRITAL DE POLÃTICA JURÃDICA",
    "acto_administrativo": "Resolución No. 310 de 2026",
    "fecha_inicio_tramite": "2026-07-20",
    "fecha_efectiva": "2026-08-03",
    "etapa_activa_id": "v_lnr_4",
    "observaciones": "Vinculación formalizada e incorporada a la nómina institucional en vigencia 2026. Verificación de antecedentes y posesión surtida conforme a la Ley 909 de 2004."
  },
  {
    "id": "TR-VINC-2026-018",
    "tipo_proceso": "VINCULACION",
    "modalidad": "PROVISIONALIDAD",
    "servidor_nombre": "MARIA GABRIELA TREJO CHAVES",
    "servidor_cedula": "1193101660",
    "cargo": "AUXILIAR ADMINISTRATIVO",
    "codigo": "407",
    "grado": "15",
    "dependencia": "DIRECCIÓN DISTRITAL DE DOCTRINA Y ASUNTOS NORMATIVOS",
    "acto_administrativo": "Resolución No. 340 de 2026",
    "fecha_inicio_tramite": "2026-07-20",
    "fecha_efectiva": "2026-08-03",
    "etapa_activa_id": "v_prov_4",
    "observaciones": "Vinculación formalizada e incorporada a la nómina institucional en vigencia 2026. Verificación de antecedentes y posesión surtida conforme a la Ley 909 de 2004."
  },
  {
    "id": "TR-VINC-2026-019",
    "tipo_proceso": "VINCULACION",
    "modalidad": "CARRERA_ADMINISTRATIVA",
    "id_plaza": 100,
    "servidor_nombre": "LEIDY JOHANNA HERRERA MENDEZ",
    "servidor_cedula": "53165390",
    "cargo": "PROFESIONAL ESPECIALIZADO",
    "codigo": "222",
    "grado": "19",
    "dependencia": "DIRECCIÓN DISTRITAL DE ASUNTOS DISCIPLINARIOS",
    "acto_administrativo": "Resolución No. 325 de 2026",
    "fecha_inicio_tramite": "2026-08-05",
    "fecha_efectiva": "2026-08-19",
    "etapa_activa_id": "v_carr_4",
    "observaciones": "Vinculación formalizada e incorporada a la nómina institucional en vigencia 2026. Verificación de antecedentes y posesión surtida conforme a la Ley 909 de 2004."
  },
  {
    "id": "TR-VINC-2026-020",
    "tipo_proceso": "VINCULACION",
    "modalidad": "CARRERA_ADMINISTRATIVA",
    "servidor_nombre": "ALBA KARINA ESTEVEZ AMAYA",
    "servidor_cedula": "52827794",
    "cargo": "AUXILIAR ADMINISTRATIVO",
    "codigo": "407",
    "grado": "20",
    "dependencia": "DESPACHO SECRETARÃA JURÃDICA",
    "acto_administrativo": "Resolución No. 312 de 2026",
    "fecha_inicio_tramite": "2026-08-18",
    "fecha_efectiva": "2026-09-01",
    "etapa_activa_id": "v_carr_4",
    "observaciones": "Vinculación formalizada e incorporada a la nómina institucional en vigencia 2026. Verificación de antecedentes y posesión surtida conforme a la Ley 909 de 2004."
  },
  {
    "id": "TR-VINC-2026-021",
    "tipo_proceso": "VINCULACION",
    "modalidad": "PROVISIONALIDAD",
    "servidor_nombre": "JESSE JOSE VILLEGAS CABRERA",
    "servidor_cedula": "1122727530",
    "cargo": "SECRETARIO",
    "codigo": "440",
    "grado": "9",
    "dependencia": "DIRECCIÓN DISTRITAL DE DOCTRINA Y ASUNTOS NORMATIVOS",
    "acto_administrativo": "Resolución No. 388 de 2026",
    "fecha_inicio_tramite": "2026-08-25",
    "fecha_efectiva": "2026-09-08",
    "etapa_activa_id": "v_prov_4",
    "observaciones": "Vinculación formalizada e incorporada a la nómina institucional en vigencia 2026. Verificación de antecedentes y posesión surtida conforme a la Ley 909 de 2004."
  },
  {
    "id": "TR-VINC-2026-022",
    "tipo_proceso": "VINCULACION",
    "modalidad": "PROVISIONALIDAD",
    "servidor_nombre": "ANGELA LISETH MUÑOZ BEDOYA",
    "servidor_cedula": "1027523637",
    "cargo": "AUXILIAR ADMINISTRATIVO",
    "codigo": "407",
    "grado": "17",
    "dependencia": "DIRECCIÓN DE GESTIÓN CORPORATIVA",
    "acto_administrativo": "Resolución No. 387 de 2026",
    "fecha_inicio_tramite": "2026-08-25",
    "fecha_efectiva": "2026-09-08",
    "etapa_activa_id": "v_prov_4",
    "observaciones": "Vinculación formalizada e incorporada a la nómina institucional en vigencia 2026. Verificación de antecedentes y posesión surtida conforme a la Ley 909 de 2004."
  },
  {
    "id": "TR-VINC-2026-023",
    "tipo_proceso": "VINCULACION",
    "modalidad": "PROVISIONALIDAD",
    "servidor_nombre": "MARTHA CLAUDIA ALDANA AVELINO",
    "servidor_cedula": "35415925",
    "cargo": "AUXILIAR SERVICIOS GENERALES",
    "codigo": "470",
    "grado": "3",
    "dependencia": "DIRECCIÓN DE GESTIÓN CORPORATIVA",
    "acto_administrativo": "Resolución No. 373 de 2026",
    "fecha_inicio_tramite": "2026-08-27",
    "fecha_efectiva": "2026-09-10",
    "etapa_activa_id": "v_prov_4",
    "observaciones": "Vinculación formalizada e incorporada a la nómina institucional en vigencia 2026. Verificación de antecedentes y posesión surtida conforme a la Ley 909 de 2004."
  },
  {
    "id": "TR-VINC-2026-024",
    "tipo_proceso": "VINCULACION",
    "modalidad": "PROVISIONALIDAD",
    "servidor_nombre": "MARIA ALEJANDRA BASTIDAS PADILLA",
    "servidor_cedula": "1030572725",
    "cargo": "AUXILIAR ADMINISTRATIVO",
    "codigo": "407",
    "grado": "9",
    "dependencia": "DIRECCIÓN DISTRITAL DE INSPECCIÓN, VIGILANCIA Y CONTROL",
    "acto_administrativo": "Resolución No. 367 de 2026",
    "fecha_inicio_tramite": "2026-08-27",
    "fecha_efectiva": "2026-09-10",
    "etapa_activa_id": "v_prov_4",
    "observaciones": "Vinculación formalizada e incorporada a la nómina institucional en vigencia 2026. Verificación de antecedentes y posesión surtida conforme a la Ley 909 de 2004."
  },
  {
    "id": "TR-VINC-2026-025",
    "tipo_proceso": "VINCULACION",
    "modalidad": "PROVISIONALIDAD",
    "servidor_nombre": "JUAN ANDRES GUERRERO RAMOS",
    "servidor_cedula": "1014976247",
    "cargo": "TECNICO OPERATIVO",
    "codigo": "314",
    "grado": "15",
    "dependencia": "DIRECCIÓN DISTRITAL DE POLÃTICA JURÃDICA",
    "acto_administrativo": "Resolución No. 386 de 2026",
    "fecha_inicio_tramite": "2026-08-27",
    "fecha_efectiva": "2026-09-10",
    "etapa_activa_id": "v_prov_4",
    "observaciones": "Vinculación formalizada e incorporada a la nómina institucional en vigencia 2026. Verificación de antecedentes y posesión surtida conforme a la Ley 909 de 2004."
  },
  {
    "id": "TR-VINC-2026-026",
    "tipo_proceso": "VINCULACION",
    "modalidad": "CARRERA_ADMINISTRATIVA",
    "servidor_nombre": "MARÍA PAULA RUEDA SOCHA",
    "servidor_cedula": "1007538666",
    "cargo": "PROFESIONAL UNIVERSITARIO",
    "codigo": "219",
    "grado": "18",
    "dependencia": "DIRECCIÓN DE GESTIÓN CORPORATIVA",
    "acto_administrativo": "Resolución No. 075 de 2026",
    "fecha_inicio_tramite": "2026-09-09",
    "fecha_efectiva": "2026-09-23",
    "etapa_activa_id": "v_carr_4",
    "observaciones": "Vinculación formalizada e incorporada a la nómina institucional en vigencia 2026. Verificación de antecedentes y posesión surtida conforme a la Ley 909 de 2004."
  },
  {
    "id": "TR-VINC-2026-027",
    "tipo_proceso": "VINCULACION",
    "modalidad": "PRACTICANTE_JUDICANTE",
    "servidor_nombre": "JUAN PABLO BARRAGÁN LONDOÑO",
    "servidor_cedula": "1018492011",
    "cargo": "JUDICANTE AD-HONOREM",
    "dependencia": "DIRECCIÓN DISTRITAL DE DOCTRINA Y ASUNTOS NORMATIVOS",
    "fecha_inicio_tramite": "2026-03-15",
    "fecha_efectiva": "2026-04-01",
    "etapa_activa_id": "v_prac_3",
    "observaciones": "Judicatura en derecho Universidad Nacional. Verificado CDP de auxilio formativo, afiliación patronal a ARL y designación de tutor institucional."
  }
];
