name: Deploy SASGE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy
        run: |
          cd /opt/administrative-requests/frontend

          git pull origin main

          npx expo export --platform web

          sudo rm -rf /var/www/administrative-requests/*
          sudo cp -r dist/* /var/www/administrative-requests/

          sudo systemctl reload nginx

          echo "Deploy completado"
