name: Deploy SASGE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build web
        run: npx expo export --platform web

      - name: Publish
        run: |
          sudo rm -rf /var/www/administrative-requests/*
          sudo cp -r dist/* /var/www/administrative-requests/
          sudo systemctl reload nginx
